Add gitleaks section to contrib doc
cyberark/conjur pull request #1844
Opened 2020-09-24 11:48 UTC by eranha

Pushing to github is a form of publication, especially when using a public repo. It is a good idea to use a hook to check for secrets before pushing code.

2020-09-24 13:36 UTC, orenbm commented on CONTRIBUTING.md
> +##### Preventing Secret Leaks
looks out of place to me. how can it be before you install git?

also - why are there 4 `#`?

2020-09-24 13:37 UTC, izgeri requested changes

2020-09-24 13:37 UTC, izgeri commented on CONTRIBUTING.md
> +Follow this [link](https://github.com/cyberark/community/blob/master/Conjur/conventions/git-tips-and-tricks.md#preventing-leaks) on how to go about configuring git check for secrets before every push
this is in a weird spot, it's inserted between the prerequisite intro sentence and the list of prerequisites, and it has 5 hashtags when the parent section has 2 (so this subsection should just have 3)

can you please:
- move it down below the prerequisites
- change the number of `#` in the title
- add it to the TOC

2020-09-24 14:17 UTC, orenbm commented on CONTRIBUTING.md
> +### Preventing Secret Leaks
i would change to `Prevent secret leaks` to maintain the language of this doc

2020-09-24 14:17 UTC, orenbm commented on CONTRIBUTING.md
> +
remove empty line

2020-09-24 14:39 UTC, orenbm approved these changes

2020-09-24 15:04 UTC, izgeri submitted a review, later dismissed

2020-09-29 08:27 UTC, nessiLahav approved these changes
LGTM

2020-09-29 09:35 UTC, nessiLahav approved these changes
LGTM

2020-09-29 10:46 UTC, nessiLahav approved these changes

2020-09-29 11:52 UTC, merged