Add new environment with default logger
cyberark/conjur pull request #2055
Opened 2021-02-28 12:44 UTC by uCatu

### What does this PR do?
- _What's changed? Why were these changes made?_
- _How should the reviewer approach this PR, especially if manual tests are required?_
- _Are there relevant screenshots you can add to the PR description?_

### What ticket does this PR close?
Resolves #[relevant GitHub issues, eg 76]

### Checklists

#### Change log
- [ ] The CHANGELOG has been updated, or
- [ ] This PR does not include user-facing changes and doesn't require a CHANGELOG update

#### Test coverage
- [ ] This PR includes new unit and integration tests to go with the code changes, or
- [ ] The changes in this PR do not require tests

#### Documentation
- [ ] Docs (e.g. `README`s) were updated in this PR, and/or there is a follow-on issue to update docs, or
- [ ] This PR does not require updating any documentation

#### API Changes
- [ ] The [OpenAPI spec](https://github.com/cyberark/conjur-openapi-spec) has been updated to meet new API changes (or an issue has been opened), or
- [ ] The changes in this PR do not affect the Conjur API

2021-02-28 13:36 UTC, orenbm commented
@uCatu can you please fix the commit messages to use an imperative mode? or are you planning to squash the second commit into the first

2021-02-28 13:39 UTC, orenbm commented
@uCatu the only differences between the new file and `appliance.rb` are:
1. You removed `config.middleware.use Rack::RememberUuid`
2. You removed `config.audit_database ||= 'postgres://:5433/audit'`

Why can't you use `RAILS_ENV=appliance` to gain what you want? do the above make it impossible in a way? if so, can you elaborate?

2021-03-02 17:39 UTC, micahlee requested changes
@uCatu , could you add some background context on this change and what problem you're trying to solve? A linked issue explaining that could go a long way.

Environments are typically `dev`, `test`, and `production`. `audit` doesn't seem at face-value to be an appropriate environment, but I don't understand what the goal is yet and where it is you need this.

2021-04-11 07:58 UTC, uCatu commented
This functionality was achieved using same method as decompose-follower.

2021-04-11 07:58 UTC, closed without merging