Add api version
cyberark/conjur pull request #2107
Opened 2021-04-12 18:38 UTC by telday

### What does this PR do?
Adds a file with the current api version to the repository. This file will help keep track of the current OpenAPI version which releases alongside Conjur.

### Checklists

#### Change log
- [ ] The CHANGELOG has been updated, or
- [x] This PR does not include user-facing changes and doesn't require a CHANGELOG update

#### Test coverage
- [ ] This PR includes new unit and integration tests to go with the code changes, or
- [x] The changes in this PR do not require tests

#### Documentation
- [ ] Docs (e.g. `README`s) were updated in this PR, and/or there is a follow-on issue to update docs, or
- [x] This PR does not require updating any documentation

#### API Changes
- [ ] The [OpenAPI spec](https://github.com/cyberark/conjur-openapi-spec) has been updated to meet new API changes (or an issue has been opened), or
- [ ] The changes in this PR do not affect the Conjur API

2021-04-12 19:31 UTC, izgeri commented
@telday can we also add this to the CHANGELOG `Added` section and link to this file in the CONTRIBUTING? both the section where you describe the openapi workflow and in the "releasing" section (I know you have a follow-up issue for the latter, but we should at least mention that this should be manually checked for now)

2021-04-12 20:30 UTC, telday commented
@izgeri Should be all set now

2021-04-12 21:15 UTC, izgeri requested changes
a couple of minor suggestions for changes - also want to flag for @alexkalish

2021-04-12 21:15 UTC, izgeri commented on app/API_VERSION
> +5.1.0
this should just be at the root dir level, right? like VERSION?

2021-04-12 21:15 UTC, izgeri commented on CHANGELOG.md
> +- New File `API_VERSION` containing the current Conjur API Version to the repository.
we need to link this to the OpenAPI spec - maybe change it to
```suggestion
- File `API_VERSION` containing the current Conjur API Version, which corresponds to a
  release of the [Conjur OpenAPI Spec](https://github.com/cyberark/conjur-openapi-spec).
```

2021-04-12 21:15 UTC, izgeri commented on CONTRIBUTING.md
> +1. Change the API_VERSION file to reflect the new API version if there has been an update to the API.
```suggestion
1. Change the API_VERSION file to reflect the correct
   [OpenAPI spec release](https://github.com/cyberark/conjur-openapi-spec/releases)
   if there has been an update to the API.
```

2021-04-13 15:18 UTC, izgeri commented on CHANGELOG.md
> +  release of the [Conjur OpenAPI Spec](https://github.com/cyberark/conjur-openapi-spec).
this also needs the link to the PR: [PR cyberark/conjur#2107](https://github.com/cyberark/conjur/pull/2107)

2021-04-14 13:19 UTC, izgeri approved these changes

2021-04-14 14:11 UTC, merged