Add JWT authenticator changelog
cyberark/conjur pull request #2259
Opened 2021-06-09 08:07 UTC by nessiLahav

### What does this PR do?
Add JWT authenticator changelog

### Checklists

#### Change log
- [ ] The CHANGELOG has been updated, or
- [ ] This PR does not include user-facing changes and doesn't require a CHANGELOG update

#### Test coverage
- [ ] This PR includes new unit and integration tests to go with the code changes, or
- [ ] The changes in this PR do not require tests

#### Documentation
- [ ] Docs (e.g. `README`s) were updated in this PR, and/or there is a follow-on issue to update docs, or
- [ ] This PR does not require updating any documentation

#### API Changes
- [ ] The [OpenAPI spec](https://github.com/cyberark/conjur-openapi-spec) has been updated to meet new API changes (or an issue has been opened), or
- [ ] The changes in this PR do not affect the Conjur API

2021-06-09 08:11 UTC, hilagross approved these changes

2021-06-09 10:00 UTC, benoaviram approved these changes

2021-06-13 06:49 UTC, shulifink requested changes

2021-06-13 06:49 UTC, shulifink commented on CHANGELOG.md
> +- JWT authenticator (`authn-jwt`) supports authenticating third-party vendors which utilize JWT.
```suggestion
- The JWT Authenticator (`authn-jwt`) supports authenticating third-party vendors that utilize JWT.
```

2021-06-13 08:48 UTC, merged