`aud` claim support
cyberark/conjur pull request #2315
Opened 2021-07-18 18:51 UTC by sashaCher

### What does this PR do?

Enables `authn-jwt` to support `aud` claim according [RFC](https://datatracker.ietf.org/doc/html/rfc7519).

### What ticket does this PR close?

### Checklists

#### Change log
- [ ] The CHANGELOG has been updated, or
- [ ] This PR does not include user-facing changes and doesn't require a CHANGELOG update

#### Test coverage
- [ ] This PR includes new unit and integration tests to go with the code changes, or
- [ ] The changes in this PR do not require tests

#### Documentation
- [ ] Docs (e.g. `README`s) were updated in this PR, and/or there is a follow-on issue to update docs, or
- [ ] This PR does not require updating any documentation

#### API Changes
- [ ] The [OpenAPI spec](https://github.com/cyberark/conjur-openapi-spec) has been updated to meet new API changes (or an issue has been opened), or
- [ ] The changes in this PR do not affect the Conjur API

2021-07-27 12:11 UTC, nessiLahav requested changes
Just add limitation that audience variable supports only singe value and not array

2021-07-27 13:31 UTC, nessiLahav commented on app/domain/authentication/authn_jwt/validate_and_decode/fetch_audience_value.rb
> +          return empty_audience_value unless audience_resource_exists?
Why? it should be similar to `FetchIssuerValue` command class

2021-07-27 13:45 UTC, nessiLahav commented
@sashaCher We need to decide what state if claim is mandatory to validate, the current behavior is:
iss,iat,nbf = if they exist in the token, we must to validate them

In this design you suggest otherwise:
If aud  exists in token is not must to validate
But if audience is configured it means it is must to be validated 

I think aud should act the same as other claims. (we can add in the future configuration of mandatory standard claim to validate)

@benoaviram @hilagross WDYT?

2021-07-27 13:46 UTC, sashaCher commented
@nessiLahav I've added limitation and emphasised that `aud` is mandatory once variable exists

2021-07-27 13:52 UTC, sashaCher commented
@nessiLahav 
1. It's a shame that we have no mechanism that allows customer to define claims mentioned by you as mandatory.
2. In any case we have to respect them if they are present
3. The behaviour should be consistent:
**Given:** As a authenticator owner I've defined the `audience` variable and provided it with valid value
**When** The authenticator receives a token without `aud` claim at all
**Then** The authentication failed

2021-07-27 14:03 UTC, nessiLahav commented
> @nessiLahav
> 
> 1. It's a shame that we have no mechanism that allows customer to define claims mentioned by you as mandatory.
> 2. In any case we have to respect them if they are present
> 3. The behaviour should be consistent:
>    **Given:** As a authenticator owner I've defined the `audience` variable and provided it with valid value
>    **When** The authenticator receives a token without `aud` claim at all
>    **Then** The authentication failed

I am OK with the decision that we are enforcing the audience by the policy but as you mention in bullet 1, i think the UX is problematic/confusing:

**exp** - is mandatory hardcoded 
**iss** - is mandatory if exists in token while `issuer` variable is optional 
**iat, nbf** - are mandatory if exist in token
**aud** - is mandatory if `audience` variable is configured
**jti** - is ignored

2021-07-28 06:48 UTC, hilagross commented
@nessiLahav @sashaCher 
if `audience` variable exists then it should must be in token and should be validated.
the variable itself should be optional, same as `iss`

I'm trying to understand if it's possible to verify `aud` claim that is in the token (same as other claims behaviour)

2021-07-28 07:10 UTC, nessiLahav approved these changes
LGTM

2021-07-29 08:00 UTC, nessiLahav approved these changes
LGTM

2021-07-29 12:14 UTC, merged