Pull up authentication failure audit
cyberark/conjur pull request #2422
Opened 2021-11-14 16:10 UTC by eranha

`AuthenticateController` is now responsible to audit all
authentication failures since all flows in `AuthenticateController` rescue errors and call `handle_authentication_error`.

A [bug](https://ca-il-jira.il.cyber-ark.com:8443/browse/ONYX-13556) on OIDC authentication failure has no audit was reported. It appears that other authn flows like gcp also don't audit failures but some do. This PR removes all of the specific failure audit and moves it to `AuthenticateController.handle_authentication_error` since all authn flows rescue the error and call `handle_authentication_error`

### Desired Outcome
All authentication failures are being audit.

### Implemented Changes
- All of the specific failure audit
- `AuthenticateController.handle_authentication_error` audot failures. 

### Connected Issue/Story

Resolves #[relevant GitHub issue(s), e.g. 76]

CyberArk internal issue link: [13556](https://ca-il-jira.il.cyber-ark.com:8443/browse/ONYX-13556)

### Definition of Done
*At least 1 todo must be completed in the sections below for the PR to be
merged.*

#### Changelog

- [ ] The CHANGELOG has been updated, or
- [ ] This PR does not include user-facing changes and doesn't require a
  CHANGELOG update

#### Test coverage

- [ ] This PR includes new unit and integration tests to go with the code
  changes, or
- [ ] The changes in this PR do not require tests

#### Documentation

- [ ] Docs (e.g. `README`s) were updated in this PR
- [ ] A follow-up issue to update official docs has been filed here: [insert issue ID]()
- [ ] This PR does not require updating any documentation

#### Behavior

- [ ] This PR changes product behavior and has been reviewed by a PO, or
- [ ] These changes are part of a larger initiative that will be reviewed later, or
- [ ] No behavior was changed with this PR

#### Security

- [ ] Security architect has reviewed the changes in this PR,
- [ ] These changes are part of a larger initiative with a separate security review, or
- [ ] There are no security aspects to these changes

2021-11-14 17:29 UTC, orenbm commented on app/controllers/authenticate_controller.rb
> +        enabled_authenticators: Authentication::InstalledAuthenticators.enabled_authenticators_str
fix indentation
```suggestion
      authenticator_input: input,
      authenticators: installed_authenticators,
      enabled_authenticators: Authentication::InstalledAuthenticators.enabled_authenticators_str
```

2021-11-14 17:30 UTC, orenbm commented on app/controllers/authenticate_controller.rb
> +    @authenticator_input ||= Authentication::AuthenticatorInput.new(
is this correct? won't it stay static for the future requests?

2021-11-14 17:31 UTC, orenbm commented on app/controllers/authenticate_controller.rb
> +    authn_info = authenticator_input
this seems redundant. if you think that `authn_info` is a better name than `authenticator_input` then let's replace the method itself. Or else just leave it as `authenticator_input`

2021-11-15 08:21 UTC, orenbm commented on app/controllers/authenticate_controller.rb
> +    handle_authentication_error(e)
you can pass `input` here instead of memoizing it

2021-11-15 08:22 UTC, orenbm requested changes
left some comments

2021-11-15 11:54 UTC, orenbm commented on app/controllers/authenticate_controller.rb
> +  def authenticator_input
i think this can stay in the same place it's implemented now at the top. Anyway, let's have it next to the other authenticator_input methods

2021-11-15 13:44 UTC, orenbm commented on app/domain/authentication/authenticate.rb
>        audit_success
what about moving this to the authn controller as well? can we align the logic here?

2021-11-15 14:28 UTC, orenbm commented on app/controllers/authenticate_controller.rb
> +    audit_success
```suggestion
    audit_success
    render_authn_token(authn_token)
```

2021-11-15 14:28 UTC, orenbm commented on app/controllers/authenticate_controller.rb
> +  end
this method is redundant. we can call `authenticate_audit_event` instead

2021-11-15 14:29 UTC, orenbm commented on app/controllers/authenticate_controller.rb
> +  def authenticate_audit_event(err)
let's make this more generic as we call this also from `validate_status`
```suggestion
  def audit_failure(err)
```

2021-11-15 14:30 UTC, orenbm commented on app/domain/authentication/authenticate.rb
>        audit_success
this should be removed, no?

2021-11-15 14:30 UTC, orenbm commented on app/domain/authentication/authenticate.rb
>      def audit_role_id
do we still use this? please verify we have no audit leftovers in the files you change

2021-11-15 14:30 UTC, orenbm commented on app/domain/authentication/authn_k8s/inject_client_cert.rb
>          audit_success
should this be removed?

2021-11-15 14:32 UTC, orenbm requested changes
left some comments

2021-11-15 14:34 UTC, orenbm commented on app/controllers/authenticate_controller.rb
> +      success: err == nil,
i prefer that we have this method duplicated with `success: true` and `success: false` than checking if the err is nil.

2021-11-15 14:47 UTC, orenbm commented on app/controllers/authenticate_controller.rb
> +  end
```suggestion
  def audit_authn_error(err)
    Audit.logger.log(
      authenticate_audit_event(err)
    )
  end
```

2021-11-15 14:48 UTC, orenbm commented on app/controllers/authenticate_controller.rb
> +  end
also - let's make the method name more generic so we have `audit_success` and `audit_failure`
```suggestion
  def audit_failure(err)
```

2021-11-15 16:15 UTC, orenbm commented on app/controllers/authenticate_controller.rb
> +  end
can we have an alignment between this and the update_config audits? there you have a method called `log_audit_event` and you give it an event as input.  we can do the same here.

2021-11-15 16:16 UTC, orenbm commented on app/controllers/authenticate_controller.rb
> +    audit_authn_error(e)
let's first log the audit event and then handle the error

2021-11-15 16:16 UTC, orenbm commented on app/controllers/authenticate_controller.rb
> +    audit_authn_error(e)
let's first log the audit event and then handle the error

2021-11-15 16:17 UTC, orenbm commented on app/controllers/authenticate_controller.rb
> +    ::Audit::Event::Authn::RoleId.new(
use either `::Audit` or `Audit`.

2021-11-15 16:18 UTC, orenbm requested changes
left some small comments

2021-11-15 19:14 UTC, orenbm commented on app/controllers/authenticate_controller.rb
> +    audit_error(e)
do we first audit the error or handle the error? let's be consistent

2021-11-15 19:17 UTC, orenbm commented on app/controllers/authenticate_controller.rb
> +      client_ip: client_ip,
does this work? don't you need to add `authenticator_input.`?

2021-11-16 10:05 UTC, orenbm commented on app/controllers/authenticate_controller.rb
> +    log_audit_event(update_config_audit_event)
i think that if we do this here then we should do this for all the calls from the `authenticate_controller` (`validate_status`, etc.)

2022-02-09 18:06 UTC, foxefj-cyber commented
@eranha - it looks like this PR is supposed to be part of the 12.5 release?  According to the story it should be done but the PR was never merged.

2022-02-14 08:37 UTC, orenbm commented
This change is nice to have and has a too high risk for the capacity we have to invest in it. Closing this PR.

2022-02-14 08:37 UTC, closed without merging