Include the supplied version in gen_versions
cyberark/conjur pull request #2606
Opened 2022-07-14 14:55 UTC by ismarc

The output of gen_versions is used for determining the list of target
versions to publish.  This will include the supplied version number
as well.

### Desired Outcome

### Implemented Changes

*Describe how the desired outcome above has been achieved with this PR. In
particular, consider:*

- Update gen_versions to include the supplied version

### Definition of Done
*At least 1 todo must be completed in the sections below for the PR to be
merged.*

#### Changelog

- [ ] The CHANGELOG has been updated, or
- [x] This PR does not include user-facing changes and doesn't require a
  CHANGELOG update

#### Test coverage

- [ ] This PR includes new unit and integration tests to go with the code
  changes, or
- [x] The changes in this PR do not require tests

#### Documentation

- [ ] Docs (e.g. `README`s) were updated in this PR
- [ ] A follow-up issue to update official docs has been filed here: [insert issue ID]()
- [x] This PR does not require updating any documentation

#### Behavior

- [ ] This PR changes product behavior and has been reviewed by a PO, or
- [ ] These changes are part of a larger initiative that will be reviewed later, or
- [x] No behavior was changed with this PR

#### Security

- [ ] Security architect has reviewed the changes in this PR,
- [ ] These changes are part of a larger initiative with a separate security review, or
- [x] There are no security aspects to these changes

2022-07-14 15:03 UTC, hughsaunders submitted a review, later dismissed

2022-07-15 13:40 UTC, jtuttle requested changes

2022-07-15 13:40 UTC, jtuttle commented on build_utils.sh
> +  echo "$version"
You'll want to change the comment above the method if you're going with this fix. It says this method is only for generating less specific versions.

2022-07-15 14:08 UTC, jtuttle approved these changes

2022-07-15 19:22 UTC, merged