Edge secure endpoint
cyberark/conjur pull request #2719
Opened 2023-02-14 21:18 UTC by amosmintzcyberark

### Desired Outcome

*Please describe the desired outcome for this PR.  Said another way, what was
the original request that resulted in these code changes?  Feel free to copy
this information from the connected issue.*

### Implemented Changes

*Describe how the desired outcome above has been achieved with this PR. In
particular, consider:*

- _What's changed? Why were these changes made?_
- _How should the reviewer approach this PR, especially if manual tests are required?_
- _Are there relevant screenshots you can add to the PR description?_

### Connected Issue/Story

Resolves #[relevant GitHub issue(s), e.g. 76]

CyberArk internal issue ID: [insert issue ID]

### Definition of Done
*At least 1 todo must be completed in the sections below for the PR to be
merged.*

#### Changelog

- [ ] The CHANGELOG has been updated, or
- [ ] This PR does not include user-facing changes and doesn't require a
  CHANGELOG update

#### Test coverage

- [ ] This PR includes new unit and integration tests to go with the code
  changes, or
- [ ] The changes in this PR do not require tests

#### Documentation

- [ ] Docs (e.g. `README`s) were updated in this PR
- [ ] A follow-up issue to update official docs has been filed here: [insert issue ID]
- [ ] This PR does not require updating any documentation

#### Behavior

- [ ] This PR changes product behavior and has been reviewed by a PO, or
- [ ] These changes are part of a larger initiative that will be reviewed later, or
- [ ] No behavior was changed with this PR

#### Security

- [ ] Security architect has reviewed the changes in this PR,
- [ ] These changes are part of a larger initiative with a separate security review, or
- [ ] There are no security aspects to these changes

2023-02-15 13:08 UTC, yoavgeva commented on app/controllers/edge_controller.rb
> +      .slice(*allowed_params).to_h.symbolize_keys
you sure you need slice? it's just do a duplicate of list

2023-02-15 13:18 UTC, yoavgeva commented on app/controllers/edge_controller.rb
> +      .slice(*allowed_params).to_h.symbolize_keys
you sure you need slice? it's just do a duplicate of list

2023-02-15 13:18 UTC, yoavgeva commented on app/controllers/edge_controller.rb
> +    options = params.permit(*allowed_params)
you sure you need slice? it's just do a duplicate of list

2023-02-15 13:18 UTC, yoavgeva commented on app/controllers/edge_controller.rb
> +    end
need to be in it's own method

2023-02-15 13:18 UTC, yoavgeva commented on app/controllers/edge_controller.rb
> +    end
need to be in it's own method

2023-02-15 13:18 UTC, yoavgeva commented on app/controllers/edge_controller.rb
> +    scope = Role.where(:role_id.like("conjur:host:data%"))
Is there no Exceptions that can be thrown? 

For example from above I saw 

`rescue ApplicationController::Forbidden
      raise
    rescue ArgumentError => e
      raise ApplicationController::UnprocessableEntity, e.message`

2023-02-15 13:18 UTC, yoavgeva commented on cucumber/api/features/step_definitions/user_steps.rb
> +    loginid = login.slice(login.index('/')+1, login.length)
I saw you fixed it @amosmintzcyberark, it does not break other tests?

2023-02-28 10:22 UTC, aloncarmel111 approved these changes

2023-02-28 10:27 UTC, aloncarmel111 requested changes
.

2023-02-28 18:30 UTC, merged