Sofia/add to the edge ongoing log the tenant
cyberark/conjur pull request #2915
Opened 2023-08-23 09:08 UTC by sofiadimant1

### Desired Outcome

*Please describe the desired outcome for this PR.  Said another way, what was
the original request that resulted in these code changes?  Feel free to copy
this information from the connected issue.*

### Implemented Changes

*Describe how the desired outcome above has been achieved with this PR. In
particular, consider:*

- _What's changed? Why were these changes made?_
- _How should the reviewer approach this PR, especially if manual tests are required?_
- _Are there relevant screenshots you can add to the PR description?_

### Connected Issue/Story

Resolves #[relevant GitHub issue(s), e.g. 76]

CyberArk internal issue ID: [insert issue ID]

### Definition of Done
*At least 1 todo must be completed in the sections below for the PR to be
merged.*

#### Changelog

- [ ] The CHANGELOG has been updated, or
- [ ] This PR does not include user-facing changes and doesn't require a
  CHANGELOG update

#### Test coverage

- [ ] This PR includes new unit and integration tests to go with the code
  changes, or
- [ ] The changes in this PR do not require tests

#### Documentation

- [ ] Docs (e.g. `README`s) were updated in this PR
- [ ] A follow-up issue to update official docs has been filed here: [insert issue ID]
- [ ] This PR does not require updating any documentation

#### Behavior

- [ ] This PR changes product behavior and has been reviewed by a PO, or
- [ ] These changes are part of a larger initiative that will be reviewed later, or
- [ ] No behavior was changed with this PR

#### Security

- [ ] Security architect has reviewed the changes in this PR,
- [ ] These changes are part of a larger initiative with a separate security review, or
- [ ] There are no security aspects to these changes

2023-08-23 09:11 UTC, liubovra approved these changes

2023-08-23 09:43 UTC, aloncarmel111 requested changes

2023-08-23 09:43 UTC, aloncarmel111 commented on app/domain/logs.rb
> +            "Requested from tenant: {9}.",
the tenant id needs to be the first parameter

2023-08-23 09:43 UTC, aloncarmel111 commented on lib/conjur/conjur_config.rb
> +        result.split("-")[1] || ""
possible to transoform it to uuid format xxxxxxxx-xxxx-Bxxx-Axxx-xxxxxxxxxxxx

2023-08-23 12:50 UTC, aloncarmel111 submitted a review, later dismissed

2023-08-23 13:20 UTC, aloncarmel111 approved these changes

2023-08-23 13:56 UTC, aloncarmel111 approved these changes

2023-08-23 14:49 UTC, aloncarmel111 approved these changes

2023-08-24 06:40 UTC, egvili approved these changes
LGTM

2023-08-24 06:41 UTC, merged